---
language: ruby
cache: bundler
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
script:
  - bin/rspec
jobs:
  fast_finish: true
  include:
    - rvm: 2.6.5
      name: Rubocop
      script:
        - bundle info rubocop
        - bin/rubocop
